@startuml

package AACCG{
class Juego {
vel_personaje
size_x
size_y
nombre
}
class GameWindow {
margen_scroll
}
class Jugador
class Tile
class EntidadFactory {
nombre
ancho_base
alto_base
crear(jugador,coordenada)
}
class SpriteSheet {
imagen
pixel_ref_x
pixel_ref_y
fps
delay
crear(entidad)
}
class Entidad {
nombre
ancho_base
alto_base
}
class Sprite {
imagen
pixel_ref_x
pixel_ref_y
fps
delay
}
class CoordenadaMapa {
x
y
}
}

package SDL {
class SDL_Window
class SDL_Point
}

Juego *-- GameWindow
GameWindow *-- CoordenadaMapa
GameWindow *-- SDL_Point : size >
Juego o-- EntidadFactory
Juego *-- Tile
Tile o-- Entidad
EntidadFactory --> Entidad
EntidadFactory --> Jugador
EntidadFactory --> CoordenadaMapa
GameWindow *-- SpriteSheet
SpriteSheet --> Sprite
Juego o-- Jugador
Jugador o-- Entidad
Entidad *-- CoordenadaMapa
Sprite *-- SDL_Point

GameWindow --> SDL_Window

@enduml
