@startuml

package Entities {
abstract class Entity {
name
position
size
solid
sightRadius
}
abstract class Structure
class Unit {
speed
orientation
strength
range
}
abstract class Building
class ProducerBuilding {
products
current
}
class UnfinishedBuilding
class TownCenter
class Flag
class Resource
class Worker
class King
}

Entity <|-- Structure

Structure <|-- Building
Building <|-- Flag
Building <|-- UnfinishedBuilding
Building <|-- ProducerBuilding
ProducerBuilding <|-- TownCenter

Structure <|-- Resource

Entity <|-- Unit
Unit <|-- King
Unit <|-- Worker


package Mixins {
class Gauge {
max
min
value
}
abstract class EntityMixin
abstract class ProgressMixin
abstract class HealthMixin
abstract class CargoMixin {
cargoType
}
}

Entity o-- Gauge : cooldown

ProducerBuilding o-- ProgressMixin

EntityMixin <|-- ProgressMixin
ProgressMixin o-- Gauge

EntityMixin <|-- HealthMixin
HealthMixin o-- Gauge

EntityMixin <|-- CargoMixin
CargoMixin o-- Gauge

HealthMixin <|-- Unit
HealthMixin <|-- Building

CargoMixin <|-- Resource
CargoMixin <|-- Worker

ProgressMixin <|-- UnfinishedBuilding


package Commands {
abstract class Command
class StopCommand
abstract class PositionalCommand {
position
}
class CreateCommand {
unitType
}
class MoveCommand
class BuildCommand {
buildingType
}
abstract class InteractionCommand
class AttackCommand
class RepairCommand
class FollowCommand
class GatherCommand
}

Command o-- Entity : subject

Command <|-- StopCommand

Command <|-- CreateCommand

Command <|-- GatherCommand

Command <|-- PositionalCommand

PositionalCommand <|-- MoveCommand
PositionalCommand <|-- BuildCommand

Command <|-- InteractionCommand

InteractionCommand o-- Entity : object

InteractionCommand <|-- AttackCommand
InteractionCommand <|-- RepairCommand
InteractionCommand <|-- FollowCommand


package Factories {
abstract class EntityFactory {
name
size
solid
sightRadius
}
class UnitFactory {
speed
strength
health
range
}
abstract class StructureFactory
abstract class BuildingFactory {
health
}
class ResourceFactory {
capacity
}
class WorkerFactory {
capacity
}
class KingFactory
class FlagFactory
class ProducerBuildingFactory {
products
}
class TownCenterFactory
}

EntityFactory <|--  UnitFactory
EntityFactory <|--  StructureFactory
StructureFactory <|--  BuildingFactory
StructureFactory <|--  ResourceFactory
ResourceFactory --> Resource

UnitFactory <|--  WorkerFactory
WorkerFactory --> Worker
UnitFactory <|--  KingFactory
UnitFactory --> Unit
KingFactory --> King
BuildingFactory <|--  FlagFactory
FlagFactory --> Flag
BuildingFactory <|-- ProducerBuildingFactory
ProducerBuildingFactory --> ProducerBuilding
ProducerBuildingFactory <|-- TownCenterFactory
TownCenterFactory --> TownCenter

@enduml

