@startuml

package Entities {
abstract class Entity {
name
position
size
}
class Structure
abstract class Unit {
speed
orientation
strength
range
}
class Building
class UnfinishedBuilding
class TownCenter
class Barracks
class Flag
class Resource
class Worker
class King
}

Entity <|-- Structure

Structure <|-- Building
Building <|-- UnfinishedBuilding
Building <|-- TownCenter
Building <|-- Barracks
Building <|-- Flag

Structure <|-- Resource

Entity <|-- Unit
Unit <|-- King
Unit <|-- Worker


package Mixins {
class Gauge {
max
min
value
}
abstract class EntityMixin
abstract class ProgressMixin
abstract class HealthMixin
abstract class CargoMixin
}

Entity o-- Gauge : cooldown

EntityMixin <|-- ProgressMixin
ProgressMixin o-- Gauge

EntityMixin <|-- HealthMixin
HealthMixin o-- Gauge

EntityMixin <|-- CargoMixin
CargoMixin o-- Gauge

HealthMixin <|-- Unit
HealthMixin <|-- Building

CargoMixin <|-- Resource
CargoMixin <|-- Worker

ProgressMixin <|-- UnfinishedBuilding


package Commands {
abstract class Command
class StopCommand
abstract class PositionalCommand {
position
}
class MoveCommand
class BuildCommand {
buildingType
}
abstract class InteractionCommand
class AttackCommand
class RepairCommand
class FollowCommand
class GatherCommand
}

Command o-- Entity : subject

Command <|-- StopCommand

Command <|-- PositionalCommand

PositionalCommand <|-- MoveCommand
PositionalCommand <|-- BuildCommand

Command <|-- InteractionCommand

InteractionCommand o-- Entity : object

InteractionCommand <|-- AttackCommand
InteractionCommand <|-- RepairCommand
InteractionCommand <|-- FollowCommand


package Factories {
abstract class EntityFactory {
name
size
}
class UnitFactory {
speed
strength
health
range
}
abstract class StructureFactory
abstract class BuildingFactory
class ResourceFactory {
capacity
}
class WorkerFactory
class KingFactory
class BarracksFactory
class FlagFactory
class TownCenterFactory
}

EntityFactory <|--  UnitFactory
EntityFactory <|--  StructureFactory
StructureFactory <|--  BuildingFactory
StructureFactory <|--  ResourceFactory

UnitFactory <|--  WorkerFactory
WorkerFactory --> Worker
UnitFactory <|--  KingFactory
KingFactory --> King
BuildingFactory <|--  BarracksFactory
BarracksFactory --> Barracks
BuildingFactory <|--  FlagFactory
FlagFactory --> Flag
BuildingFactory <|--  TownCenterFactory
TownCenterFactory --> TownCenter

@enduml

