@startuml
package AACCG{
class Game

abstract class Board
class SmartBoard
class RemoteBoard

abstract class Entity
class SmartEntity
class DumbEntity

abstract class Player
class SmartPlayer
class DumbPlayer

abstract class Client
class GraphicClient
class NetworkClient

class IsoView
class Minimap
class Hud

class Socket
}

Game o-- Board
Game *-- Client
Client --> Player

Board o-- Entity : Terreno
Board *-- Entity : Entidades
Board o-- Player

Client <|-- GraphicClient
Client <|-- NetworkClient

Board <|-- SmartBoard
Board <|-- RemoteBoard

Entity <|-- SmartEntity
SmartBoard ..> SmartEntity
Entity <|-- DumbEntity
RemoteBoard ..> DumbEntity

Player <|-- SmartPlayer
SmartBoard ..> SmartPlayer
Player <|-- DumbPlayer
RemoteBoard ..> DumbPlayer

NetworkClient o-- Socket
RemoteBoard o-- Socket
Socket .. Socket

GraphicClient o-- IsoView
GraphicClient o-- Minimap
GraphicClient o-- Hud

@enduml

